SET(CTEST_PROJECT_NAME "NiftyReg")
SET(CTEST_NIGHTLY_START_TIME "22:00:00 GMT")
SET(CTEST_TEST_TIMEOUT "3600")

IF(NOT DEFINED CTEST_DROP_METHOD)
	SET(CTEST_DROP_METHOD "http")
ENDIF(NOT DEFINED CTEST_DROP_METHOD)

IF(CTEST_DROP_METHOD STREQUAL "http")
	SET(CTEST_DROP_SITE "cdash.cmiclab.cs.ucl.ac.uk")
	SET(CTEST_DROP_LOCATION "/submit.php?project=NiftyReg")
	SET(CTEST_DROP_SITE_CDASH TRUE)
ENDIF(CTEST_DROP_METHOD STREQUAL "http")
