name: linux
on: [push, pull_request]
jobs:
  build:
    runs-on: [self-hosted, Linux, gpu]
    strategy: 
      max-parallel: 2
      matrix:
        build_config: [Release, Debug]
        include:
          - build_config: Release
            with_coverage: OFF
          - build_config: Debug
            with_coverage: ON

    steps:
      # - name: Get git and cmake
      #   run: |
      #     apt-get -qq update
      #     apt-get install -qq -y --no-install-recommends git cmake gcc g++ make
      #   shell: bash

      - name: Install Catch2
        run: |
          export GIT_SSL_NO_VERIFY=1
          git clone --depth 1 https://github.com/catchorg/Catch2.git
          cd Catch2
          cmake -Bbuild -H. -DBUILD_TESTING=OFF
          cmake --build build/ --target install --config Release
        shell: bash

      - name: checkout the commited version of NiftyReg
        run: |
          export GIT_SSL_NO_VERIFY=1
          git clone --depth 1 --branch  ${{ github.ref_name }} https://github.com/KCL-BMEIS/niftyreg.git
        shell: bash

      - name: Configure NiftyReg
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=g++ \
                -DCMAKE_C_COMPILER=gcc \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_config }} \
                -DBUILD_ALL_DEP=ON \
                -DUSE_CUDA=OFF \
                -DUSE_OPENCL=OFF \
                -DUSE_SSE=ON \
                -DUSE_OPENMP=ON \
                -DBUILD_TESTING=ON \
                -DWITH_COVERAGE=${{ matrix.with_coverage }} \
                ../niftyreg
        shell: bash

      - name: Build NiftyReg
        run: cmake --build build --config ${{ matrix.build_config }}
        shell: bash

      - name: Run tests
        run: ctest -V
        working-directory: build
        shell: bash