name: linux
on: [push, pull_request]
jobs:
  build:
    runs-on: [self-hosted, ubuntu-20.04, gpu]
    strategy: 
      max-parallel: 2
      matrix:
        build_config: [Release, Debug]
        include:
          - build_config: Release
            with_coverage: OFF
          - build_config: Debug
            with_coverage: ON

    steps:
      - uses: actions/checkout@v3

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Install Catch2
        run:  |
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          cmake -Bbuild -H. -DBUILD_TESTING=OFF
          sudo cmake --build build/ --target install --config Release
        shell: bash

      - name: Configure NiftyReg
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=g++ \
                -DCMAKE_C_COMPILER=gcc \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_config }} \
                -DBUILD_ALL_DEP=ON \
                -DUSE_CUDA=OFF \
                -DUSE_OPENCL=OFF \
                -DUSE_SSE=ON \
                -DUSE_OPENMP=ON \
                -DBUILD_TESTING=ON \
                -DWITH_COVERAGE=${{ matrix.with_coverage }} \
                ..
        shell: bash

      - name: Build NiftyReg
        run: cmake --build build --config ${{ matrix.build_config }}
        shell: bash

      - name: Run tests
        run: ctest -V
        working-directory: build
        shell: bash