name: windows
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      max-parallel: 1
      matrix:
        os: [windows-2022]
        include:
          - os: windows-2022
            c-compiler: "cl.exe"
            cxx-compiler: "cl.exe"
            use_cuda: "OFF"
            use_opencl: "OFF"
            use_openmp: "ON"
            vcvars64: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
    steps:
      - uses: actions/checkout@v3

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Install Catch2
        run:  |
          call "${{ matrix.vcvars64 }}"
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          cmake -Bbuild -H. -DBUILD_TESTING=OFF
          cmake --build build/ --target install --config Release
        shell: cmd


      - name: Configure NiftyReg
        run: |
          mkdir build
          cd build
          call "${{ matrix.vcvars64 }}"
          cmake -DCMAKE_CXX_COMPILER=${{ matrix.cxx-compiler }} -DCMAKE_C_COMPILER=${{ matrix.c-compiler }} -DCMAKE_BUILD_TYPE=Release -DBUILD_ALL_DEP=ON -DUSE_CUDA=${{ matrix.use_cuda }} -DUSE_OPENCL=${{ matrix.use_opencl }} -DUSE_SSE=ON  -DUSE_OPENMP=${{ matrix.use_openmp }}  -DBUILD_TESTING=ON ..
        shell: cmd


      - name: Build NiftyReg
        run: |
          call "${{ matrix.vcvars64 }}"
          cmake --build build --config Release
        shell: cmd


      - name: Run tests
        run: |
          call "${{ matrix.vcvars64 }}"
          ctest -V
        working-directory: build
        shell: cmd

